//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bucatarie
    {
        public int Id { get; set; }
        public int ChelnerId { get; set; }
        public int MasaNr { get; set; }
        public string Comanda { get; set; }
    
        public virtual Chelner Chelner { get; set; }
    }
}
