//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chelner
    {
        public Chelner()
        {
            this.Bucataries = new HashSet<Bucatarie>();
            this.Clients = new HashSet<Client>();
        }
    
        public int Id { get; set; }
        public string ChelnerName { get; set; }
        public int Comanda { get; set; }
    
        public virtual ICollection<Bucatarie> Bucataries { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
    }
}
