//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantDataContext : DbContext
    {
        public RestaurantDataContext()
            : base("name=RestaurantDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bucatarie> Bucataries { get; set; }
        public DbSet<Chelner> Chelners { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<Ingrediente> Ingredientes { get; set; }
        public DbSet<MeniuClient> MeniuClients { get; set; }
    }
}
